[project]
name = "weather-tool"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "requests>=2.32.5",
]

[tool.ruff]
line-length = 150

[tool.ruff.format]
quote-style = "single"
